from typing import Protocol, runtime_checkable


@runtime_checkable
class ObjectStore(Protocol):
    async def put(self, key: str, data: bytes, content_type: str = "application/octet-stream") -> str: ...
    async def put_json(self, key: str, obj: dict) -> str: ...
    async def get(self, uri: str) -> bytes: ...
    async def exists(self, uri: str) -> bool: ...
    async def presign_public(self, uri: str, ttl_s: int = 3600) -> str: ...
